const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const todayISO=()=>new Date().toLocaleDateString('en-CA');
let state={tasks:[],categories:[],priorities:[],tab:'all',selectedTask:null,calendarDate:new Date(),selectedDate:todayISO(),taskOrderMode:false};
const DEFAULT_CATS=[{id:'work',name:'工作',color:'#3b82f6',order:1},{id:'family',name:'家庭',color:'#22c55e',order:2},{id:'personal',name:'個人',color:'#8b5cf6',order:3}];
const DEFAULT_PRI=[{id:'high',name:'高',color:'#ef4444',order:1},{id:'medium',name:'中',color:'#f59e0b',order:2},{id:'low',name:'低',color:'#22c55e',order:3}];
const DEFAULT_TABS=['all','open','done','today','future'];
const TAB_LABEL={all:'全部',open:'未完成',done:'已完成',today:'今天',future:'未來'};
async function init(){await openDB();if(!(await DB.all('categories')).length)await DB.bulkPut('categories',DEFAULT_CATS);if(!(await DB.all('priorities')).length)await DB.bulkPut('priorities',DEFAULT_PRI);state.categories=await DB.all('categories');state.priorities=await DB.all('priorities');await ensureSetting('tabs',DEFAULT_TABS);await ensureSetting('theme','system');applyTheme((await DB.get('settings','theme')).value);bind();await refresh();renderManagers();renderTabs();await renderTabManager();renderCalendar();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});setTimeout(()=>checkVersion(false),700)}
async function ensureSetting(key,value){if(!(await DB.get('settings',key)))await DB.put('settings',{key,value})}
function bind(){
 $('#menuBtn').onclick=openDrawer;$('#overlay').onclick=closeAll;$('#addBtn').onclick=addTask;$('#taskInput').addEventListener('input',autoGrow);$('#search').addEventListener('input',renderTasks);
 $('#categorySelect').onchange=()=>{};$('#prioritySelect').onchange=()=>{};
 $('#drawerClose').onclick=closeDrawer;$$('[data-nav]').forEach(b=>b.onclick=()=>{showPage(b.dataset.nav);closeDrawer()});
 $('#themeSelect').onchange=async e=>{applyTheme(e.target.value);await DB.put('settings',{key:'theme',value:e.target.value})};
 $('#exportBtn').onclick=async()=>{await exportBackup();$('#backupStatus').textContent='✓ 備份完整性檢查通過';$('#backupStatus').classList.remove('hidden');toast('備份已匯出')};
 $('#importInput').onchange=handleImport;$('#checkVersionBtn').onclick=()=>checkVersion(true);$('#applyUpdateBtn').onclick=applyUpdate;$('#laterUpdateBtn').onclick=()=>$('#updateBox').classList.add('hidden');
 $('#addCategory').onclick=()=>editManager('categories');$('#addPriority').onclick=()=>editManager('priorities');
 $('#prevMonth').onclick=()=>{state.calendarDate.setMonth(state.calendarDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{state.calendarDate.setMonth(state.calendarDate.getMonth()+1);renderCalendar()};$('#todayMonth').onclick=()=>{state.calendarDate=new Date();state.selectedDate=todayISO();renderCalendar()};
 $('#saveTaskEdit').onclick=saveTaskEdit;$('#cancelTaskEdit').onclick=()=>closeModal('taskModal');$('#saveManager').onclick=saveManager;$('#cancelManager').onclick=()=>closeModal('managerModal');
 $('#actionEdit').onclick=()=>{openTaskEdit(state.selectedTask);closeSheet()};$('#actionDelete').onclick=()=>deleteTask(state.selectedTask);$('#actionOrder').onclick=()=>{state.taskOrderMode=true;toast('排序模式：使用 ↑ ↓ 調整，完成後再點其他功能');closeSheet();renderTasks()};
}
async function refresh(){state.tasks=(await DB.all('tasks')).sort((a,b)=>(a.sortOrder??0)-(b.sortOrder??0));fillSelects();renderTasks();renderCalendarTasks()}
function fillSelects(){const c=$('#categorySelect'),p=$('#prioritySelect');c.innerHTML='<option value="">分類</option>'+state.categories.sort((a,b)=>a.order-b.order).map(x=>`<option value="${x.id}">${x.name}</option>`).join('');p.innerHTML='<option value="">優先級</option>'+state.priorities.sort((a,b)=>a.order-b.order).map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}
function autoGrow(e){e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,150)+'px'}
async function addTask(){const content=$('#taskInput').value.trim();if(!content)return;const now=new Date().toISOString();const t={id:uid('task'),content,completed:false,categoryId:$('#categorySelect').value||null,priorityId:$('#prioritySelect').value||null,dueDate:$('#dueDate').value||null,sortOrder:state.tasks.length?Math.max(...state.tasks.map(x=>x.sortOrder||0))+100:100,createdAt:now,updatedAt:now,completedAt:null};await DB.put('tasks',t);$('#taskInput').value='';$('#taskInput').style.height='';$('#dueDate').value='';await refresh();toast('已新增待辦')}
function filterTasks(){let arr=[...state.tasks],t=todayISO();if(state.tab==='open')arr=arr.filter(x=>!x.completed);if(state.tab==='done')arr=arr.filter(x=>x.completed);if(state.tab==='today')arr=arr.filter(x=>x.dueDate===t);if(state.tab==='future')arr=arr.filter(x=>x.dueDate&&x.dueDate>t);const q=$('#search').value.trim().toLowerCase();if(q)arr=arr.filter(x=>x.content.toLowerCase().includes(q)||catName(x.categoryId).toLowerCase().includes(q));return arr}
function catName(id){return state.categories.find(x=>x.id===id)?.name||''}function priName(id){return state.priorities.find(x=>x.id===id)?.name||''}function colorOf(list,id){return list.find(x=>x.id===id)?.color||'#94a3b8'}
function renderTasks(){const list=$('#taskList'),items=filterTasks();$('#taskCount').textContent=`${items.length} 項`;if(!items.length){list.innerHTML='<div class="empty">目前沒有待辦事項</div>';return}list.innerHTML=items.map(t=>`<div class="task ${t.completed?'done':''} ${state.taskOrderMode?'ordering':''}" data-id="${t.id}"><input class="check" type="checkbox" ${t.completed?'checked':''} aria-label="完成"><div><div class="task-title">${esc(t.content)}</div><div class="meta">${t.categoryId?`<span class="chip" style="background:${hexAlpha(colorOf(state.categories,t.categoryId),.14)};color:${colorOf(state.categories,t.categoryId)}">${esc(catName(t.categoryId))}</span>`:''}${t.priorityId?`<span class="chip" style="background:${hexAlpha(colorOf(state.priorities,t.priorityId),.14)};color:${colorOf(state.priorities,t.priorityId)}">${esc(priName(t.priorityId))}</span>`:''}${t.dueDate?`<span class="chip">${t.dueDate.replaceAll('-','/')}</span>`:''}</div></div>${state.taskOrderMode?'<div class="task-order-actions"><button data-move="-1">↑</button><button data-move="1">↓</button></div>':'<button class="more" aria-label="更多">⋮</button>'}</div>`).join('');
 $$('.task').forEach(el=>{const id=el.dataset.id;el.querySelector('.check').onchange=()=>toggleTask(id);const more=el.querySelector('.more');if(more)more.onclick=()=>openSheet(id);el.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveTask(id,Number(b.dataset.move)))})}
async function moveTask(id,dir){const visible=filterTasks();const idx=visible.findIndex(x=>x.id===id),target=idx+dir;if(idx<0||target<0||target>=visible.length)return;const a=visible[idx],b=visible[target],tmp=a.sortOrder;a.sortOrder=b.sortOrder;b.sortOrder=tmp;a.updatedAt=b.updatedAt=new Date().toISOString();await DB.put('tasks',a);await DB.put('tasks',b);await refresh();}
async function saveDomOrder(){const ids=$$('.task').map(x=>x.dataset.id);for(let i=0;i<ids.length;i++){const t=state.tasks.find(x=>x.id===ids[i]);if(t){t.sortOrder=(i+1)*100;t.updatedAt=new Date().toISOString();await DB.put('tasks',t)}}state.taskOrderMode=false;await refresh();toast('排序已儲存')}
async function toggleTask(id){const t=state.tasks.find(x=>x.id===id);t.completed=!t.completed;t.completedAt=t.completed?new Date().toISOString():null;t.updatedAt=new Date().toISOString();await DB.put('tasks',t);await refresh()}
function openSheet(id){state.selectedTask=id;$('#sheet').classList.add('show');$('#overlay').classList.add('show')}
function closeSheet(){$('#sheet').classList.remove('show');$('#overlay').classList.remove('show')}
function openTaskEdit(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;$('#editContent').value=t.content;$('#editDate').value=t.dueDate||'';$('#editCompleted').checked=t.completed;$('#editCategory').innerHTML='<option value="">未分類</option>'+state.categories.map(x=>`<option value="${x.id}" ${x.id===t.categoryId?'selected':''}>${x.name}</option>`).join('');$('#editPriority').innerHTML='<option value="">無</option>'+state.priorities.map(x=>`<option value="${x.id}" ${x.id===t.priorityId?'selected':''}>${x.name}</option>`).join('');openModal('taskModal')}
async function saveTaskEdit(){const t=state.tasks.find(x=>x.id===state.selectedTask);if(!t)return;t.content=$('#editContent').value.trim();t.categoryId=$('#editCategory').value||null;t.priorityId=$('#editPriority').value||null;t.dueDate=$('#editDate').value||null;const was=t.completed;t.completed=$('#editCompleted').checked;if(t.completed&&!was)t.completedAt=new Date().toISOString();if(!t.completed)t.completedAt=null;t.updatedAt=new Date().toISOString();await DB.put('tasks',t);closeModal('taskModal');await refresh();toast('已修改')}
async function deleteTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;await DB.delete('tasks',id);closeSheet();await refresh();showUndo(t)}
function showUndo(t){const bar=$('#undo');bar.innerHTML='待辦已刪除　<button id="undoBtn" style="border:0;background:transparent;color:#8db7ff;font-weight:700">復原</button>';bar.classList.add('show');const timer=setTimeout(()=>bar.classList.remove('show'),5000);$('#undoBtn').onclick=async()=>{clearTimeout(timer);await DB.put('tasks',t);bar.classList.remove('show');await refresh();toast('已復原')}}
async function renderTabs(){const st=await DB.get('settings','tabs'),tabs=st?.value||DEFAULT_TABS;$('#tabs').innerHTML=tabs.map(id=>`<button class="tab ${state.tab===id?'active':''}" data-tab="${id}">${TAB_LABEL[id]}</button>`).join('');$$('.tab').forEach(b=>{b.onclick=()=>{state.tab=b.dataset.tab;renderTabs();renderTasks()}})}
async function renderTabManager(){const root=$('#tabManager');if(!root)return;const st=await DB.get('settings','tabs'),tabs=st?.value||DEFAULT_TABS;root.innerHTML=tabs.map((id,i)=>`<div class="tab-manager-row"><strong>${TAB_LABEL[id]}</strong><button class="order-btn" data-tab-up="${id}" ${i===0?'disabled':''}>↑</button><button class="order-btn" data-tab-down="${id}" ${i===tabs.length-1?'disabled':''}>↓</button></div>`).join('');$$('[data-tab-up]').forEach(b=>b.onclick=()=>moveTab(b.dataset.tabUp,-1));$$('[data-tab-down]').forEach(b=>b.onclick=()=>moveTab(b.dataset.tabDown,1))}
async function moveTab(id,dir){const st=await DB.get('settings','tabs'),tabs=[...(st?.value||DEFAULT_TABS)],i=tabs.indexOf(id),j=i+dir;if(i<0||j<0||j>=tabs.length)return;[tabs[i],tabs[j]]=[tabs[j],tabs[i]];await DB.put('settings',{key:'tabs',value:tabs});await renderTabs();await renderTabManager();toast('頁籤順序已儲存')}
function openDrawer(){$('#drawer').classList.add('show');$('#overlay').classList.add('show')}function closeDrawer(){$('#drawer').classList.remove('show');$('#overlay').classList.remove('show')}function closeAll(){closeDrawer();closeSheet();$$('.modal').forEach(m=>m.classList.remove('show'));$('#overlay').classList.remove('show')}
function showPage(id){$$('.page').forEach(p=>p.classList.remove('active'));$('#'+id).classList.add('active');if(id==='calendarPage')renderCalendar();if(id==='managePage')renderManagers();if(id==='tabPage')renderTabManager()}
function openModal(id){$('#'+id).classList.add('show');$('#overlay').classList.add('show')}function closeModal(id){$('#'+id).classList.remove('show');$('#overlay').classList.remove('show')}
function renderManagers(){for(const [store,root] of [['categories','#categoryManager'],['priorities','#priorityManager']]){$(root).innerHTML=state[store].sort((a,b)=>a.order-b.order).map(x=>`<div class="manager-row"><span>☷</span><span class="swatch" style="background:${x.color}"></span><span>${esc(x.name)}</span><button class="icon-btn" data-edit-${store}="${x.id}">✎</button><button class="icon-btn" data-del-${store}="${x.id}">🗑</button></div>`).join('')}$$('[data-edit-categories]').forEach(b=>b.onclick=()=>editManager('categories',b.dataset.editCategories));$$('[data-edit-priorities]').forEach(b=>b.onclick=()=>editManager('priorities',b.dataset.editPriorities));$$('[data-del-categories]').forEach(b=>b.onclick=()=>deleteManager('categories',b.dataset.delCategories));$$('[data-del-priorities]').forEach(b=>b.onclick=()=>deleteManager('priorities',b.dataset.delPriorities))}
function editManager(type,id=null){const item=id?state[type].find(x=>x.id===id):null;$('#managerType').value=type;$('#managerId').value=id||'';$('#managerTitle').textContent=(id?'修改':'新增')+(type==='categories'?'分類':'優先級');$('#managerName').value=item?.name||'';$('#managerColor').value=item?.color||'#3b82f6';openModal('managerModal')}
async function saveManager(){const type=$('#managerType').value,id=$('#managerId').value||uid(type==='categories'?'cat':'pri'),arr=state[type],old=arr.find(x=>x.id===id);const item={id,name:$('#managerName').value.trim(),color:$('#managerColor').value,order:old?.order||(arr.length+1)};if(!item.name)return;await DB.put(type,item);state[type]=await DB.all(type);closeModal('managerModal');fillSelects();renderManagers();renderTasks()}
async function deleteManager(type,id){if(type==='categories'){for(const t of state.tasks.filter(x=>x.categoryId===id)){t.categoryId=null;t.updatedAt=new Date().toISOString();await DB.put('tasks',t)}}else{for(const t of state.tasks.filter(x=>x.priorityId===id)){t.priorityId=null;t.updatedAt=new Date().toISOString();await DB.put('tasks',t)}}await DB.delete(type,id);state[type]=await DB.all(type);await refresh();renderManagers()}
function renderCalendar(){const d=state.calendarDate,y=d.getFullYear(),m=d.getMonth();$('#monthLabel').textContent=`${y} 年 ${m+1} 月`;const first=new Date(y,m,1),last=new Date(y,m+1,0),start=first.getDay(),cells=[];for(let i=0;i<start;i++)cells.push('');for(let day=1;day<=last.getDate();day++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,has=state.tasks.some(t=>t.dueDate===iso),today=iso===todayISO(),sel=iso===state.selectedDate;cells.push(`<button class="day ${has?'has':''} ${today?'today':''} ${sel?'selected':''}" data-date="${iso}">${day}</button>`)}$('#calendarGrid').innerHTML='<div class="day-name">日</div><div class="day-name">一</div><div class="day-name">二</div><div class="day-name">三</div><div class="day-name">四</div><div class="day-name">五</div><div class="day-name">六</div>'+cells.join('');$$('[data-date]').forEach(b=>b.onclick=()=>{state.selectedDate=b.dataset.date;renderCalendar();renderCalendarTasks()});renderCalendarTasks()}
function renderCalendarTasks(){const root=$('#calendarTasks');if(!root)return;const arr=state.tasks.filter(t=>t.dueDate===state.selectedDate);$('#selectedDateLabel').textContent=state.selectedDate||'';root.innerHTML=arr.length?arr.map(t=>`<div class="task ${t.completed?'done':''}"><input class="check" type="checkbox" ${t.completed?'checked':''} disabled><div><div class="task-title">${esc(t.content)}</div><div class="meta">${t.categoryId?`<span class="chip">${esc(catName(t.categoryId))}</span>`:''}${t.priorityId?`<span class="chip">${esc(priName(t.priorityId))}</span>`:''}</div></div><span></span></div>`).join(''):'<div class="empty">這天沒有待辦</div>'}
async function handleImport(e){const file=e.target.files[0];if(!file)return;try{const obj=JSON.parse(await file.text());await validateBackup(obj);const mode=confirm(`備份日期：${obj.exportedAt||'未知'}\n待辦：${obj.tasks.length} 筆\n分類：${obj.categories.length} 個\n優先級：${obj.priorities.length} 個\n\n按「確定」合併資料；按「取消」不匯入。`)?'merge':null;if(!mode)return;await importBackup(obj,mode);state.categories=await DB.all('categories');state.priorities=await DB.all('priorities');await refresh();renderManagers();toast('備份匯入完成')}catch(err){alert('匯入失敗：'+err.message)}finally{e.target.value=''}}
function applyTheme(v){document.documentElement.dataset.theme=v==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):v;$('#themeSelect').value=v}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),2200)}
function esc(s=''){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function hexAlpha(hex,a){if(!/^#([A-Fa-f0-9]{6})$/.test(hex))return hex;const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);return `rgba(${r},${g},${b},${a})`}
window.addEventListener('DOMContentLoaded',init);
